### ISSUE TITLE
Tracker for FCOS and containers/ CI

### ISSUE THREAD

**Issue by cgwalters** [containers/automation#92]
This has come up a few times, most recently in the context of "there are no F36 traditional cloud images" but there [are for FCOS](https://builds.coreos.fedoraproject.org/browser?stream=rawhide&arch=x86_64).

Also of note here: FCOS' CI is ensuring that systemd and podman and OS upgrades all work before we ship any image to a cloud.

As I understand things, the containers/ org has invested a lot in Cirrus CI, and I think the core problem here boils down to "Cirrus doesn't support Ignition"?  Or relatedly, it relies on integration with the [GCP guest agent](https://github.com/GoogleCloudPlatform/guest-agent)?  Or is it that it uses cloud-init?

At a quick glance at [their custom VM page](https://cirrus-ci.org/guide/custom-vms/) I'm not finding any information about this.

It may work today to do e.g. `rpm-ostree install -A google-guest-agent && systemctl daemon-reload && systemctl start google-startup-scripts` or so via Ignition config.

Alternatively of course, there are a *lot* of CI systems and flows which can work with a generic "provision instance", "ssh into instance" style.  For example, using e.g. Terraform for provisioning/teardown scheduled via nearly anything (GH actions, a Prow job, etc.).

**Comment by cevich** [comment]
Some points of clarification:

> FCOS' CI is ensuring that systemd and podman and OS upgrades all work before we ship any image to a cloud.

The first thing we do in podman CI is build podman from source.  Same for buildah, skopeo, etc.  They all use the same one-size-fits-all (golang) VM image.  In any case, if the OS requires starting up podman-dependent containers to boot, that's a non-starter (since we will be replacing it and clobbering it's storage & settings)

> invested a lot in Cirrus CI

Slightly true.  Some things depend on data provided by Cirrus-CI, but variable-references are easily changed.  More importantly/correct is that containers-org CI scripts and tests assume a _general-purpose_ execution environment.  Especially our system-tests.

> it relies on integration with the GCP guest agents?

It's not necessarily specific to GCE, AWS, Azure, etc. (all supported) do the same thing (to the best of my knowledge).  In other words, Cirrus-CI is making cloud-API calls, the effect of those (cloud-services, cloud-init, etc.) is an implementation detail.  Therefor this isn't anything we have any control over, it's internal to Cirrus-CI, and up to the cloud API authors what happens under the hood.

> Or is it that it uses cloud-init?

Other than intended interactions with the cloud-specific services/APIs, we depend on cloud-init only for simple things (i.e. resizing disks).

> At a quick glance at their custom VM page I'm not finding any information about this.

This is a very complex topic and maintenance-heavy subject, [mostly realized/implemented in the automation_images repo.](https://github.com/containers/automation_images). There are both VM and Container images which sometimes must be coordinated.  The VM images are cloud-specific internally and behind-the-scenes with integration in life-cycle management systems.

> It may work today to do

That may work to get Cirrus-CI running basic things, but will certainly fail trying to execute testing across our repos.  They all have a very long history of assuming a full/bloated general-purpose OS.  Secondarily, we strive to test as close to the user-experience as possible.  At some point, we will have customized FCOS to such an extent, it no-longer reflects how anybody actually uses it :disappointed: 

> work with a generic

I have extensive experience working with orchestration systems that operate via system services (like ssh) and cloud-APIs.  I don't universally despise the higher-level tools.  They have their place.  It's simply in the context of testing container-tools, the simpler the orchestration tooling, the better it is for the developers.  The big-name tools are ***not*** generic in all respects. They are laser-focused on ease-of-orchestration, at the cost of runtime system-observability.

So in the case system-level testing of container services, operating at a low-level (at system boot) is a big advantage.  Chiefly in reduced complexity and improved debug-ability by developers (i.e. orchestration non-experts).  Arguably Cirrus-CI and it's agent are the orchestration system. However in practice they're very simplistic, less feature-bloated, and "command-pattern" focused.  Therefore far easier for the non-experts to work with and (more importantly) within.

**Comment by cevich** [comment]
Thinking about this more...is really going to be a steep uphill-battle.  Most containers-org repos CI assumes the build environment == test environment.  i.e. The `Makefile` is heavily leveraged for both building, verification, and test execution.  Running the integration tests (e.g. for podman) would be especially difficult due to dependence on ginkgo.  However, the podman & buildah system-tests are designed to be run stand-alone and tend to be much less picky about their environment.

So, rather than trying to run the kitchen-sink verification, we could maybe do more limited verification on FCOS with just the system-tests. It's still going to be quite a bit of work to tool up, but seems more doable given the lower environment requirements.

**Comment by cevich** [comment]
Stepping back for a second @cgwalters 

> Also of note here: FCOS' CI is ensuring that systemd and podman and OS upgrades all work before we ship any image to a cloud.

This is key, and likely where the biggest return on effort lies.  Since FCOS CI already has the ability to test in a meaningful way  (I'm assuming) with all the components, this seems an ideal space to attach an additional element:  Periodically execute FCOS CI but injecting the latest podman/buildah/skopeo binaries from upstream.  The results will be immediately comparable to other FCOS-centric testing, and also close enough to upstream tooling development where feedback can influence changes before end-users find problems.

Cirrus-CI cannot (and will probably never) support rebooting a test-VM at runtime, but I'm betting that's not an issue for FCOS CI (based on what you described above).  If (more) test (content) is needed, I would suggest running the podman system tests (can be consumed as a blob of bash scripts + minimal config).  In any case, we've already got binary artifacts that can be downloaded from Cirrus-CI on any podman branch (I think)...ya, [for example, this binary.zip](https://api.cirrus-ci.com/v1/artifact/github/containers/podman/Build%20for%20fedora-35/binary.zip?branch=main)

We've got other formats too, like a "installed" tarball (includes docs) and I even think we're building test RPMs...okay, we don't archive those, but would be easy to add if helpful ([log](https://cirrus-ci.com/task/5060612915986432?logs=main#L6153-L6160))

Whatcha thinking?

**Comment by cgwalters** [comment]
>  this seems an ideal space to attach an additional element: Periodically execute FCOS CI but injecting the latest podman/buildah/skopeo binaries from upstream. 

Yes!  Definitely - this strongly relates to https://github.com/coreos/fedora-coreos-tracker/issues/910 which we're picking up again.

>  They all have a very long history of assuming a full/bloated general-purpose OS. Secondarily, we strive to test as close to the user-experience as possible. At some point, we will have customized FCOS to such an extent, it no-longer reflects how anybody actually uses it disappointed

This is all on track to fundamentally change with https://github.com/coreos/enhancements/blob/main/os/coreos-layering.md bear in mind.

You will be able to do e.g. something like:
```
FROM quay.io/coreos-assembler/fcos:testing-devel
RUN rpm-ostree copr enable podman && rpm-ostree install podman
```

And get a container image...and then *boot it* - and upgrade it!  And even live apply changes from that pulled container image without rebooting.

**Comment by cevich** [comment]
> Yes! Definitely - this strongly relates to https://github.com/coreos/fedora-coreos-tracker/issues/910 which we're picking up again.

In case it helps, Lokesh is doing continuous RPM builds of podman 'main' in his `rhcontainerbot/podman-next` COPR.

On that note, I'm going to close this issue.  If it becomes necessary to test downstream podman consumers, in upstream CI, we can certainly re-open / revisit this topic.
